let dailyChartDays=window.matchMedia("(max-width:760px)").matches?60:120;
function defenseValues(a){
 const i=a.length-1,t=a[i],low=end=>end>=3?Math.min(...a.slice(end-3,end).map(b=>b.low)):null;
 return [{name:'三日低',key:'low',today:low(i),next:low(i+1)},{name:'五日線 MA5',key:'five',today:i>=5?ma(a,i-1,5):null,next:ma(a,i,5)},{name:'月線 MA20',key:'month',today:i>=20?ma(a,i-1,20):null,next:ma(a,i,20)}];
}
function renderDefenseChart(s){
 const rows=defenseValues(s.bars),price=v=>v===null?'—':fmt(v);
 document.getElementById('guard').innerHTML=`<div class="defense-table-wrap"><table class="defense-table"><thead><tr><th>防守線</th><th>昨日值（今天用）</th><th>今收距離</th><th>今日判定</th><th>明日防守值（今收後定案）</th></tr></thead><tbody>${rows.map(r=>{const delta=r.today===null?null:(s.t.close/r.today-1)*100;return `<tr class="defense-${r.key}"><td>${r.name}${r.date?`<small>紅 K：${esc(r.date)}</small>`:''}</td><td class="defense-price">${price(r.today)}</td><td class="${delta>=0?'up':'down'}">${delta===null?'—':(delta>=0?'+':'')+fmt(delta)+'%'}</td><td><span class="defense-status ${delta===null?'unknown':delta>=0?'held':'broken'}">${delta===null?'資料不足':delta>=0?'✓ 守住':'● 跌破'}</span></td><td class="defense-price">${price(r.next)}${r.disabled?'<small>今日跌破，明日不啟用</small>':''}</td></tr>`;}).join('')}</tbody></table></div><p class="defense-note">三日低：今天用前3個交易日最低價，不含今天；明日用含今天的近3日最低價。五日線：5日收盤均線，明日防守值採今日MA5。月線：20日收盤均線，明日防守值採今日MA20。收盤等於防守價視為守住，低於才判定跌破。日線採未還原價格。</p>`;
 renderDailyChart(s,rows);
}
function cumulativeVolumeZone(b,count=24){
 const floor=Math.min(...b.map(v=>v.low)),ceiling=Math.max(...b.map(v=>v.high));
 if(!Number.isFinite(floor)||ceiling<=floor)return null;
 const size=(ceiling-floor)/count,volumes=Array(count).fill(0);
 for(const bar of b){if(!Number.isFinite(bar.volume)||bar.volume<=0)continue;if(bar.high===bar.low){volumes[Math.min(count-1,Math.max(0,Math.floor((bar.close-floor)/size)))]+=bar.volume;continue;}for(let k=0;k<count;k++){const overlap=Math.max(0,Math.min(bar.high,floor+(k+1)*size)-Math.max(bar.low,floor+k*size));volumes[k]+=bar.volume*overlap/(bar.high-bar.low);}}
 const peak=Math.max(...volumes);if(peak<=0)return null;const k=volumes.indexOf(peak);return {low:floor+k*size,high:floor+(k+1)*size,volume:peak,mid:floor+(k+.5)*size};
}
function renderDailyChart(s,rows=defenseValues(s.bars)){
 const a=s.bars,start=Math.max(0,a.length-dailyChartDays),b=a.slice(start),mobile=window.matchMedia("(max-width:760px)").matches,w=mobile?400:1000,h=mobile?480:500,l=mobile?8:24,r=mobile?52:70,top=24,volBottom=h-28,plotHeight=volBottom-top-18,bottom=top+plotHeight*.75,volTop=bottom+18;
 const colors={5:'#c8a343',20:'#589dc3',60:'#a780c4',120:'#e28335'},lineColors={low:'#d83c4a',month:'#5ba9a5',five:'#287fe0'};
 const vals=b.flatMap((v,k)=>[v.high,v.low,ma(a,start+k,5),ma(a,start+k,20),ma(a,start+k,60),ma(a,start+k,120)]).concat(rows.map(x=>x.next)).filter(x=>x!==null&&Number.isFinite(x));
 let hi=Math.max(...vals),lo=Math.min(...vals),pad=(hi-lo)*.08||hi*.02;hi+=pad;lo-=pad;
 const y=v=>bottom-(v-lo)/(hi-lo)*(bottom-top),step=(w-l-r)/b.length,x=k=>l+(k+.5)*step;
 const zone=cumulativeVolumeZone(b);let svg=zone?`<rect class="volume-zone" x="${l}" y="${y(zone.high)}" width="${(w-l-r)*.85}" height="${Math.max(3,y(zone.low)-y(zone.high))}" fill="#ee939c" opacity=".28" stroke="#d96675" stroke-width="1"><title>累計大量區估算 ${fmt(zone.low)}–${fmt(zone.high)} 元，分攤量 ${fmt(zone.volume,0)} 張</title></rect>`:'';for(let k=0;k<5;k++){const v=lo+(hi-lo)*k/4;svg+=`<path d="M${l} ${y(v)}H${w-r}" stroke="#e0e0e5"/><text x="${w-r+8}" y="${y(v)+4}" fill="#777" font-size="12">${fmt(v,1)}</text>`;}
 const vmax=Math.max(1,...b.map(v=>v.volume));b.forEach((v,k)=>{const color=v.close>v.open?'#c94450':v.close<v.open?'#29836c':'#85858b';svg+=`<g><title>${esc(v.date)} 開${fmt(v.open)} 高${fmt(v.high)} 低${fmt(v.low)} 收${fmt(v.close)} 量${fmt(v.volume,0)}張</title><path d="M${x(k)} ${y(v.high)}V${y(v.low)}" stroke="${color}"/><rect x="${x(k)-step*.28}" y="${Math.min(y(v.open),y(v.close))}" width="${Math.max(.8,step*.56)}" height="${Math.max(1,Math.abs(y(v.open)-y(v.close)))}" fill="${color}"/><rect x="${x(k)-step*.28}" y="${volBottom-v.volume/vmax*(volBottom-volTop)}" width="${Math.max(.8,step*.56)}" height="${v.volume/vmax*(volBottom-volTop)}" fill="${color}" opacity=".5"/></g>`;});
 [5,20,60,120].forEach(n=>{const points=b.map((v,k)=>{const m=ma(a,start+k,n);return m===null?null:`${x(k)},${y(m)}`;}).filter(Boolean);svg+=`<polyline points="${points.join(' ')}" fill="none" stroke="${colors[n]}" stroke-width="1.6"/>`;});
 const used=[];rows.filter(q=>q.next!==null).forEach(q=>{const yy=y(q.next);let labelY=yy-6;while(used.some(z=>Math.abs(z-labelY)<15))labelY-=15;used.push(labelY);svg+=`<path class="defense-line defense-line-${q.key}" d="M${l} ${yy}H${w-r}" stroke="${lineColors[q.key]}" stroke-width="1.2" stroke-dasharray="${q.key==='low'?'3 3':'8 5'}"/><text x="${l+3}" y="${Math.max(14,labelY)}" fill="${lineColors[q.key]}" font-size="13" paint-order="stroke" stroke="white" stroke-width="3">${q.key==='month'?'明日守月線':q.name} ${fmt(q.next)}</text>`;});
 [0,Math.floor((b.length-1)/3),Math.floor((b.length-1)*2/3),b.length-1].forEach(k=>{svg+=`<text x="${x(k)}" y="${h-5}" text-anchor="middle" fill="#777" font-size="11">${esc(b[k].date.slice(5))}</text>`;});
 svg+=`<path id="daily-crosshair" d="M0 ${top}V${volBottom}" stroke="#888" stroke-dasharray="3 4" visibility="hidden"/><rect id="daily-hit-area" x="${l}" y="${top}" width="${w-l-r}" height="${volBottom-top}" fill="transparent"/>`;
 const chart=document.getElementById('chart');chart.innerHTML=`<div class="daily-chart-toolbar"><div class="daily-legend"><span style="color:${colors[5]}">— MA5</span><span style="color:${colors[20]}">— MA20</span><span style="color:${colors[60]}">— MA60</span><span style="color:${colors[120]}">— MA120</span><span style="color:${lineColors.month}">╌ 月線</span><span style="color:${lineColors.five}">╌ 五日防守線</span><span style="color:${lineColors.low}">╌ 三日低</span></div><div class="daily-range">${[60,120,240].map(n=>`<button data-days="${n}" class="${dailyChartDays===n?'active':''}" aria-pressed="${dailyChartDays===n}">${n}天</button>`).join('')}</div></div><div class="daily-readout" aria-live="polite"></div><div class="daily-volume-zone-note">${zone?`▰ 累計大量區（估算） ${fmt(zone.low)}–${fmt(zone.high)} 元 · 分攤量 ${fmt(zone.volume,0)} 張`:"累計大量區：資料不足"}</div><div class="daily-defense-values">${rows.filter(q=>q.next!==null).map(q=>`<span style="color:${lineColors[q.key]}">╌ ${q.name} ${fmt(q.next)}</span>`).join("　")}</div><div class="daily-plot"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(s.code+' '+s.name)} 最近${b.length}日日線、MA5、MA20、MA60、MA120、成交量與明日防守線">${svg}</svg></div><p class="daily-chart-note">滑過或點選 K 棒查看當日開高低收與成交量；虛線為明日防守價。手機點選 K 棒可查看數值。顯示最近 ${b.length} 個交易日，資料不足不補造。淡紅橫柱為顯示期間24個等寬價位區中累計量最大的區間；以每日成交量按高低價重疊比例分攤估算，非逐筆成交的實際價量分布。</p>`;
 const plot=chart.querySelector('.daily-plot');plot.scrollLeft=plot.scrollWidth-plot.clientWidth;const readout=chart.querySelector('.daily-readout');function show(k){const v=b[k],prev=a[start+k-1],change=prev?(v.close/prev.close-1)*100:null;readout.innerHTML=`${esc(v.date)}　開 ${fmt(v.open)}　高 ${fmt(v.high)}　低 ${fmt(v.low)}　收 <b>${fmt(v.close)}</b>　<span class="${change>=0?'up':'down'}">${change===null?'—':(change>=0?'+':'')+fmt(change)+'%'}</span>　量 ${fmt(v.volume,0)} 張`;const cross=chart.querySelector('#daily-crosshair');cross.setAttribute('transform',`translate(${x(k)},0)`);cross.setAttribute('visibility','visible');}show(b.length-1);
 chart.querySelectorAll('[data-days]').forEach(button=>button.onclick=()=>{dailyChartDays=+button.dataset.days;renderDailyChart(s,rows);});
 const hit=chart.querySelector('#daily-hit-area');function inspect(e){const rect=chart.querySelector('svg').getBoundingClientRect(),px=(e.clientX-rect.left)/rect.width*w,k=Math.max(0,Math.min(b.length-1,Math.floor((px-l)/step)));show(k);}hit.addEventListener('pointermove',inspect);hit.addEventListener('click',inspect);hit.addEventListener('pointerleave',()=>show(b.length-1));
}
