/* Confirmed announcements and official cumulative warnings are separate states. */
(()=>{
 const root=document.getElementById('prison');let data=null,query='',market='all';
 const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const day=s=>new Date(s+'T12:00:00Z'),iso=d=>d.toISOString().slice(0,10),add=(s,n)=>{const d=day(s);d.setUTCDate(d.getUTCDate()+n);return iso(d);};
 const closed=s=>[0,6].includes(day(s).getUTCDay())||data.closed_dates.includes(s);
 const next=s=>{for(let i=1;i<15;i++){const d=add(s,i);if(Number(d.slice(0,4))!==data.calendar_year)return null;if(!closed(d))return d;}return null;};
 const selected=r=>market==='all'||r.market===market;
 const stock=r=>`<button class="prison-stock" data-prison-code="${e(r.code)}">${e(r.code)} ${e(r.name)}</button>`;
 function latest(pool=data.disposals){const map=new Map();for(const r of pool){const old=map.get(r.code);if(!old||r.end>old.end||r.end===old.end&&r.announcement_date>old.announcement_date)map.set(r.code,r);}return [...map.values()].filter(selected);}
 function status(r){return r.start>data.as_of?'即將處置':r.end>=data.as_of?'處置中':'已期滿';}
 function remaining(r){let n=0;for(let d=data.as_of>r.start?data.as_of:r.start;d<=r.end;d=add(d,1))if(!closed(d))n++;return n;}
 function card(r){const release=next(r.end);return `<article class="prison-stock-card">${stock(r)}<span class="prison-badge ${r.start>data.as_of?'future':''}">${status(r)}</span><p>${e(r.market)} · ${r.minutes.length?r.minutes.map(x=>x+' 分鐘').join('／')+'撮合':'撮合間隔請查公告'}</p><div class="prison-dates"><span>處置期間<strong>${r.start} ～ ${r.end}</strong></span><span>預計出關<strong>${release||'交易日曆待更新'}</strong></span>${r.end>=data.as_of?`<span>剩餘交易日<strong>${remaining(r)} 日（含當日）</strong></span>`:''}</div><small>公告日 ${r.announcement_date} · ${e(r.reason)}</small><details><summary>查看處置公告</summary><p class="prison-notice">${e(r.detail)}</p><a href="${e(r.source)}" target="_blank" rel="noopener">官方來源 ↗</a></details></article>`;}
 function search(){const host=root.querySelector('#prison-result');if(!query){host.innerHTML='';return;}const rs=data.disposals.filter(r=>selected(r)&&(r.code.includes(query)||r.name.includes(query))),ws=data.warnings.filter(r=>selected(r)&&(r.code.includes(query)||r.name.includes(query)));host.innerHTML=`<h3>查詢結果 · ${e(query)}</h3><p class="prison-muted">收錄 ${data.history_started} 起建立快照及官方目前提供的公告；查無資料不代表從未處置。</p><div class="prison-card-grid">${rs.sort((a,b)=>b.start.localeCompare(a.start)).map(card).join('')}${ws.map(warningCard).join('')}</div>${!rs.length&&!ws.length?'<p>目前留存資料無符合公告。</p>':''}`;bindStocks(host);}
 function warningCard(r){return `<article class="prison-stock-card prison-warning">${stock(r)}<span class="prison-badge warning">注意累計預警</span><p>${e(r.market)} · 官方資料 ${r.date}</p><p>${e(r.detail)}</p><small>次一營業日若再達納入計算的注意標準，可能公告處置；處置中個股也可能再受處置。尚非確定公告。</small><p><a href="${e(r.source)}" target="_blank" rel="noopener">查看官方預警 ↗</a></p></article>`;}
 function bindStocks(host=root){host.querySelectorAll('[data-prison-code]').forEach(b=>b.onclick=()=>{query=b.dataset.prisonCode;root.querySelector('#prison-query').value=query;search();root.querySelector('#prison-search-card').scrollIntoView({behavior:'smooth',block:'start'});});}
 function render(){const rows=latest(),active=latest(data.disposals.filter(r=>r.start<=data.as_of&&r.end>=data.as_of)),future=rows.filter(r=>r.start>data.as_of),newToday=active.filter(r=>r.start===data.as_of),warn=data.warnings.filter(selected),monday=add(data.as_of,-((day(data.as_of).getUTCDay()+6)%7));
  const calendar=Array.from({length:3},(_,w)=>{const start=add(monday,w*7);return `<section class="prison-week"><h3>${['本週','下週','下下週'][w]} ${start.slice(5)} ～ ${add(start,4).slice(5)}</h3><div class="prison-days">${Array.from({length:5},(_,i)=>{const d=add(start,i),rs=rows.filter(r=>next(r.end)===d);return `<article class="prison-day ${d===data.as_of?'today':''}"><h4>${d.slice(5)}（${'一二三四五'[i]}）</h4>${closed(d)?'<span class="prison-muted">休市</span>':rs.map(stock).join('')||'<span class="prison-muted">目前留存無出關公告</span>'}</article>`;}).join('')}</div></section>`;}).join('');
  const groups=STOCK_GROUPS.map(g=>({name:g.sub,rows:rows.filter(r=>r.end>=data.as_of&&g.codes.includes(r.code))})).filter(g=>g.rows.length>=2);
  const list=(title,rs,open=false)=>`<details class="prison-panel" ${open?'open':''}><summary>${title} <small>${rs.length} 檔</small></summary><div class="prison-card-grid">${rs.map(card).join('')||'<p>目前沒有符合公告。</p>'}</div></details>`;
  root.innerHTML=`<div class="etf-heading"><div><p class="eyebrow">OFFICIAL DISPOSAL WATCH</p><h2>處置股名單</h2><p>處置期間、出關日曆與注意累計預警。每日 18:40 另更新晚間公告（依官方發布及排程狀況）。</p></div><button id="prison-refresh" class="ghost">重新載入公告</button></div><p class="prison-muted">狀態日 ${data.as_of} · 快照擷取 ${e(data.updated_at.slice(0,16).replace('T',' '))}（台灣時間） · 上市預警 ${data.warning_dates['上市']}／上櫃預警 ${data.warning_dates['上櫃']||'未提供日期'}</p><div class="prison-stats"><article><span>處置中</span><strong>${active.length}</strong></article><article><span>今日新進</span><strong>${newToday.length}</strong></article><article><span>即將處置</span><strong>${future.length}</strong></article><article><span>官方累計預警</span><strong>${warn.length}</strong></article></div><div class="prison-panel" id="prison-search-card"><h3>個股處置紀錄查詢</h3><div class="prison-controls"><form id="prison-search"><input id="prison-query" placeholder="輸入代號或中文名稱" aria-label="查詢處置股" value="${e(query)}"><button>查詢</button></form><label>市場 <select id="prison-market"><option value="all">上市＋上櫃</option><option value="上市" ${market==='上市'?'selected':''}>上市</option><option value="上櫃" ${market==='上櫃'?'selected':''}>上櫃</option></select></label></div><div id="prison-result"></div></div><details class="prison-panel" open><summary>出關時間表 <small>未來三週</small></summary><p class="prison-muted">公告末日後的下一個交易日為預計恢復日，排除週末與證交所休市日；停牌、延長或公告更正會影響日期。</p>${calendar}</details><details class="prison-panel"><summary>同族群集中處置 <small>${groups.length} 組</small></summary><p class="prison-muted">使用你提供的分類，同族群至少兩檔處置中或已公告即將處置。</p><div class="prison-card-grid">${groups.map(g=>`<article class="prison-stock-card"><h3>${e(g.name)} · ${g.rows.length} 檔</h3>${g.rows.map(r=>`<p>${stock(r)} <small>${status(r)} · 出關 ${next(r.end)||'待確認'}</small></p>`).join('')}</article>`).join('')||'<p>目前沒有符合的同族群。</p>'}</div></details>${list('今日新進處置',newToday)}${list('即將處置 · 已公告',future,true)}${list('目前處置中',active)}<details class="prison-panel"><summary>注意累計預警 <small>${warn.length} 檔</small></summary><p class="prison-muted">直接採用交易所累計預警，不另標示高低機率或未驗證的明日價量門檻。</p><div class="prison-card-grid">${warn.map(warningCard).join('')||'<p>目前沒有官方預警資料。</p>'}</div></details><details class="prison-panel"><summary>處置規則與資料口徑</summary><p>注意股與處置股是不同狀態。上市主要累計條件為第一款連續 3 個營業日，或第一至第八款連續 5 日、10 日內 6 日、30 日內 12 日；符合後仍以官方正式公告為準。</p><p>撮合間隔與處置期依每檔原始公告，包含預收款券及個別加重措施；不一律套用固定天數。剩餘交易日包含狀態日，依公告期間和交易日曆估算。</p><p>歷史僅涵蓋已留存公告，未收錄者不標為「無前科」。同族群使用你的分類；已期滿個股不計入目前集中處置。上櫃預警與處置直接採櫃買公告。</p><a href="https://www.twse.com.tw/zh/announcement/punish.html" target="_blank" rel="noopener">證交所處置公告 ↗</a> · <a href="https://www.tpex.org.tw/zh-tw/announce/market/disposal.html" target="_blank" rel="noopener">櫃買公告 ↗</a> · <a href="https://twse-regulation.twse.com.tw/TW/law/DOC01_print.aspx?FLCODE=FL007225&FLNO=6" target="_blank" rel="noopener">上市處置規則 ↗</a></details>`;
  root.querySelector('#prison-refresh').onclick=load;root.querySelector('#prison-search').onsubmit=ev=>{ev.preventDefault();query=root.querySelector('#prison-query').value.trim();search();};root.querySelector('#prison-market').onchange=ev=>{market=ev.target.value;render();};bindStocks();search();
 }
 async function load(){root.innerHTML='<p role="status">正在載入官方處置公告…</p>';try{const r=await fetch('prison-data.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('公告快照尚未載入');data=await r.json();if(!Array.isArray(data.disposals)||!data.as_of)throw Error('公告格式錯誤');render();}catch(err){root.innerHTML=`<article class="prison-panel"><h2>處置股名單</h2><p>${e(err.message)}</p><button id="prison-retry">重新載入</button></article>`;root.querySelector('#prison-retry').onclick=load;}}
 load();
})();
